package com.replus.api.common.error

enum class ErrorCode {
    UNAUTHENTICATED,
    INVALID_REQUEST,
    RESOURCE_NOT_FOUND,
    ROOM_MEMBER_REQUIRED,
    ROOM_OWNER_REQUIRED,
    ROOM_FULL,
    INVITE_LINK_NOT_FOUND,
    INVITE_LINK_EXPIRED,
    INVITE_LINK_USAGE_LIMIT_REACHED,
    MISSION_EDIT_LIMIT_REACHED,
    MISSION_ALREADY_HAS_RESPONSE,
    INVALID_DURATION,
    INVALID_AUDIO_REQUIRED,
    RESPONSE_ALREADY_EXISTS,
    RESPONSE_RELEASE_LOCKED,
    RESPONSE_NOT_VISIBLE,
    CANNOT_REMOVE_OWNER,
    INTERNAL_ERROR,
}
